services:
  - type: web
    name: jjproject
    runtime: java
    envVars:
      - key: JAVA_VERSION
        value: "21"
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/jjproject-0.0.1-SNAPSHOT.jar
